#!/usr/bin/env python3.8

import urllib.parse
import sys
import subprocess

if __name__ == '__main__':
    msg = " ".join(sys.argv[1:])
    if msg == "":
        msg = "Done!"
    msg = urllib.parse.quote(msg)
    print("Message is ", msg)
    subprocess.run(['open', '-g', f'hammerspoon://alert?msg={msg}'])
